### ISSUE TITLE
Extra zeros in keys

### ISSUE THREAD

**Issue by Proheeler** [offscale/liboffkv#2]
In case of your addition of \000 in key paths, it can't be used with etcdctl. Etcd don't find key /test/init and /test/\000init the same. But in list of keys they don't have any difference/

**Comment by SamuelMarks** [comment]
Are you recommending we remove this support; or that we contribute this support to `etdctl`?

**Comment by SamuelMarks** [comment]
@Proheeler Are you recommending we remove this support; or that we contribute this support to `etcdctl`?

**Comment by shdown** [comment]
> we remove this support

We can’t: we use this encoding to work around some limitations/oddities of etcd.

> we contribute this support to etcdctl?

I don’t think it’s possible: `\0` (that is, the NUL byte) can not be passed in arguments to a Unix process, because the arguments are zero-terminated. Changing etcdctl to interpret escapes like `\` `0` would break backward compatibility.

---

Anything other than the NUL byte *can* be passed in arguments though, so what can be done is, we use `\1` instead of `\0`. Valid liboffkv key may not contain either, so this is fine. The `\1` byte can be represented in shell as `$(printf '\1')` or, in bash and zsh, as `$'\1'`. One problem is, this would not be backward-compatible with respect to stuff written by older versions of liboffkv, but hopefully this would not make much impact at this point. In theory, we can introduce compile-time switch like `OLD_ETCD_SENTINEL` or something.

**Comment by SamuelMarks** [comment]
@shdown Soon backwards-compatibility will be important to maintain for offkv… but is it important now?

Until Mesos, Kubernetes, and other systems depend on offkv, I don't think we need to care about backwards-compatibility?

**Comment by shdown** [comment]
@SamuelMarks I guess you’re right.
